### PR TITLE
README: add table with ringbuffer properties

### PR DESCRIPTION
**Pull request by tertsdiepraam**
I thought an overview of features of the ringbuffers was missing, even though the descriptions technically cover most of it. The README currently also lacks some info about where powers of two are important, so I added a bit of that here too.

I'm not quite sure what should be in here exactly and how it should look. So consider this PR a request for feedback and I'll open it as a draft.

### CODE REVIEW

**Comment by NULLx76** [comment]
Technically all the ringbuffers are `no_std`, just some need `alloc` which is actually reasonably available on embedded platforms, so might be nice to be specific about that.

**Comment by NULLx76** [comment]
Additionally some quite of performance comparison might be neat as well, @jonay2000 you ran some benchmarks right?

**Comment by jonay2000** [comment]
yup, working on it :)

**Comment by jonay2000** [comment]
See #113, based on this branch

**Comment by tertsdiepraam** [comment]
@jonay2000 shall I just let you fix the table and close this then?

**Pull request closed without merging**
