### PR TITLE
remove array-init

### PR DESCRIPTION
**Pull request by jonay2000**
dependencyless woohoo!

### CODE REVIEW

**Comment by jonay2000** [comment]
somehow the MSRV doesn't even change

**Review by NULLx76 — COMMENTED** [review]
Any reason for keeping the array-init as an option even?

**Comment by jonay2000** [comment]
no, I reverted that. Thought it would change the MSRV, but then I actually checked

**Comment by NULLx76** [comment]
We bumped the MSRV with the edition update anyways

**Pull request merged**
